#!/bin/sh

if [[ $1 == "on" ]]; then

uci set system.@led[0].trigger='netdev'
uci set system.@led[1].trigger='netdev'
uci set system.@led[2].trigger='netdev'
uci set system.@led[3].trigger='default-on'

elif [[ $1 == "off" ]]; then

uci set system.@led[0].trigger='none'
uci set system.@led[1].trigger='none'
uci set system.@led[2].trigger='none'
uci set system.@led[3].trigger='none'

fi

/etc/init.d/led restart
